name: Auto-add assignees to issues
on:
 issues:
    types:
      - reopened
      - opened
jobs:
  add_label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
  add_assignee:
    runs-on: ubuntu-latest
    needs: add_label
    permissions:
      contents: read
      issues: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set assignees
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |
            let issue_number = context.payload.issue.number;
            const labels = (await github.rest.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })).data.map(label => label.name);
            const labelToAssignees = {
              'product: CLion': ['gowrojisunil'],
              'product: IntelliJ': ['gowrojisunil'],
              'product: GoLand': ['gowrojisunil'],
              'product: Android Studio': ['gowrojisunil'],
              'product: PyCharm': ['gowrojisunil']
              };
            const assignees = labels.some(label => label.startsWith('product:'))
              ? labels.reduce((acc, label) => {
                  const assignee = label in labelToAssignees ? labelToAssignees[label] : [];
                  return acc.concat(assignee);
                }, [])
              : ['sgowroji', 'satyanandak', 'iancha1992'];

            if (assignees.length > 0) {
              await github.rest.issues.addAssignees({
                issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                assignees,
              });
            }
